#!/bin/sh -ex

PROJECT=mkautodoc

find ${PROJECT} -type f -name "*.py[co]" -delete
find ${PROJECT} -type d -name __pycache__ -delete
find tests -type d -name __pycache__ -delete
rm -rf dist htmlcov .pytest_cache ${PROJECT}.egg-info
