#!/bin/sh -ex

if [ "${CONTINUOUS_INTEGRATION}" = "true" ]; then
    BIN_PATH=""
else
    rm -rf venv
    python -m venv venv
    BIN_PATH="venv/bin/"
fi

${BIN_PATH}pip install -r requirements.txt
${BIN_PATH}pip install -e .
